spring:
  application:
    name: face_recognition_resource_server
  cloud:
    config:
      uri: http://localhost:8181
      username: config
      password: configserver123
  config:
    import: configserver:http://localhost:8181
server:
  port: 8282
keySetURI: http://localhost:8080/oauth2/jwks

