spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      show_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  application:
    name: face_recognition_resource_server
  #  cloud:
  #    config:
  #      uri: http://localhost:8181
  #      username: config
  #      password: configserver123
  #  config:
  #    import: configserver:http://localhost:8181
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
server:
  port: 8282
keySetURI: http://localhost:8080/oauth2/jwks

front-end-url: ${FRONT_END_URL_PREFIX}

RSA:
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyqXw22wiQQOxvjFCCH+z+nTYvM0ZMqDKse3ATHQVAKIL07OQe1nZa0EbiIjrT5xluOiaqbgz+QuDJM1eMMrYo2EHbWIFbhxbh8IjgxAOH6CsqaGn03Ql2yZYFhBIR8caqiiVX9ZZJE9vUtE8Th7XlGtwf+NHiWt2gOuZLCA9xoXzgZXub1Kqvtv9mfXZcg9Xmyp1HQozvzeyA1Vg6VyW0SI3/KJ29KE7LVJ+5NnMbsiaIazesBzZsx+uq2Mpy9dd/JoGrmqebO1PBRwu9eBBHA4zZ3TWawL7RyybHaxUFZgbhi5uXI8lv27tOCDK95bw+JnD7qrNTZWk05oWvy4Z1AgMBAAECggEAOpOE7TtNCHawzjXT44XyHtyOelU2VEXFL3XdHfci1JEztnfApzerYETvKI8OeJFJbjFUogYo7mgg6PaTWpz5ylR06ySObOLSpstFJWQ+wB1noaTQMH8T7kVTkYVmo0mA2EMo0TjsyBLhvVBMqNuS0IXI7BaZQbyG81S8UpdW8OrzziGAepktUk1H97Uv3uc6XawT13z5TMHRbI2bEBV1uB9HE8RTalVYiBh2JvLDJDdq3hsSkK8YaFjHTI5r+p1jD0Y5OZZQALFZWEljeJ3scC/J2WMMkaqTrCQ/MH23O4e5FPdlo9jPO6u25F2VR/OFD0J/3Jpvek0MDsxYGFfzFQKBgQDIgrRMH61xkeXMiOCLb44+KsoOdB4j/3IHiWl5kfPXRwiqKrMKTEsWpx2KfOY2/ritKfbx8CBdmmeTcEb445kIQH94hDO9cQm1T869oPPWrLvvjIvkUygVZ8HMz7iRUSrcpLDi/KGDWG4Pz/p98F1RO6GtSl0qZJAmdlsXq9AU+wKBgQDkGujUUQQc6/wiWk4QD6DhMssOnxdj5wRPpEKRX8ngvOVaCrk8AbtD94yKWNxeS5N82oRrh1cmIKyTZwxu1rNGTqNQBY8whJs5y+zypWrrK5gkWOAoOg9h7ra8DFiBkYaQAykDjYFR2FfreHjXwLEXx64Chtle5BSIXFfawo+XTwKBgQCz6TNFqpbB9Jsw7xArjKkg9tveJCp3OllikdVmE6OrYj1QEogbkWE+riw/etpGNkAWgDTn2QHxev28uV21LOK/GMBHrreOH8MKQNXMKIMh+FOZGY7cDBFHQ5YM48VD/oRq/gsJYIy7gbkfzwl/vxC8NrlW+AaoZxtAp6oMj0lhyQKBgQCtb6B0Pp1n+C4fWJZeM+PZFqu6FFDOjwqCG5zZuAFhNX8VdW3eKFrglMpxLptvvvsHRYbF04P544IUGZgkdm6dGJGn+HIlK85ypZEl9YxT/zOQ/1qAe5TSm5SpaqGo8qNjwGNg5ijbuCkxSspnEYYVVKgEF9ATDExoWf4awTA4lQKBgGXaacJOy9iC/+WOISgZVdMVG3fjoDSQ/Ho7AwAM930gSjF7pvl6y5lcNMZcASBhUNAvT/B9sQAa4GCwIiAXK2NTmHSQGuHeGBlm78uaye/NSGLp1O0/pe8GUar7w70loaUXeGx9gMjQBHU0d6XVKEWWDjj1lsBdbjq3aCHnL8JJ
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsql8NtsIkEDsb4xQgh/s/p02LzNGTKgyrHtwEx0FQCiC9OzkHtZ2WtBG4iI60+cZbjomqm4M/kLgyTNXjDK2KNhB21iBW4cW4fCI4MQDh+grKmhp9N0JdsmWBYQSEfHGqoolV/WWSRPb1LRPE4e15RrcH/jR4lrdoDrmSwgPcaF84GV7m9Sqr7b/Zn12XIPV5sqdR0KM783sgNVYOlcltEiN/yidvShOy1SfuTZzG7ImiGs3rAc2bMfrqtjKcvXXfyaBq5qnmztTwUcLvXgQRwOM2d01msC+0csmx2sVBWYG4YublyPJb9u7TggyveW8PiZw+6qzU2VpNOaFr8uGdQIDAQAB