spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      show_sql: true
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  application:
    name: face_recognition_resource_server
  #  cloud:
  #    config:
  #      uri: http://localhost:8181
  #      username: config
  #      password: configserver123
  #  config:
  #    import: configserver:http://localhost:8181
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
server:
  port: 8282
keySetURI: http://localhost:8080/oauth2/jwks

front-end-url: ${FRONT_END_URL_PREFIX}
shift-control-acknowledgement-queue-name: ${SHIFT_CONTROL_ACKNOWLEDGEMENT_QUEUE_NAME}
user-control-acknowledgement-queue-name: ${USER_CONTROL_ACKNOWLEDGEMENT_QUEUE_NAME}
